services:
  - type: web
    name: svetlana-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port 10000
    envVars:
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: svetlana_service_key.json